Fix `maxAge` start on Promise settlement
sindresorhus/p-memoize pull request #24
Opened 2021-08-08 19:50 UTC by krystofwoldrich

This is PR base on issue https://github.com/sindresorhus/p-memoize/issues/22.

I've tried to keep the dependency on mem at firt, but I've not found any solution where it would make sense. After I added the maxAge map here to the `p-memoize` there wasn't basically any reason to keep mem in here. Maybe just for the `clear` function but in my opinien it is cleaner to have here `cacheStore` then to have dependency just for that purpose.

The only change is in the maxAge, all other behaviour should be unchanged.
Alltho the code would be cleaner if we would create from every function -> async function but I would rather have a bit more complicated code and keep the behaviour.

Let me know what you think or if you see any other nice, cleaner solutions.

2021-09-05 21:26 UTC, sindresorhus requested changes

2021-09-05 21:26 UTC, sindresorhus commented on index.js
> +	if (!isNaN(maxAge)) {
It should fail loudly with a `TypeError` if `maxAge` doesn't pass `Number.isSafeInteger`.

2021-09-05 21:26 UTC, sindresorhus commented on index.js
> +		if (result && result instanceof Promise) {
`instanceof` is not a good way to check for promises.

```suggestion
		if (result && typeof result.then === 'function') {
```

2021-09-05 21:26 UTC, sindresorhus commented on index.js
> +		let resultError = null;
```suggestion
		let resultError;
```

2021-09-05 21:26 UTC, sindresorhus commented on index.js
> +		if (result && result instanceof Promise) {
Why are you checking for a promise at all? You can just use `Promise.resolve()`.

2021-09-05 21:53 UTC, krystofwoldrich commented on index.js
> +		if (result && result instanceof Promise) {
Because `Promise.resolve()` returns a promise and I think it is better to keep the function working as it is now. That means when it gets a non-promise returning function it won't change it to a promise returrning function.

2021-09-05 21:54 UTC, krystofwoldrich commented on index.js
> +	if (!isNaN(maxAge)) {
OK. Thanks, this if condition didn't make sense.

2021-09-05 22:02 UTC, sindresorhus commented on index.js
> +		if (result && result instanceof Promise) {
The docs are pretty clear about it only accepting promise-returning functions though, even though we didn't actually validate that:

> Promise-returning or async function to be memoized.

2021-09-05 22:07 UTC, krystofwoldrich commented on index.js
> +		if (result && result instanceof Promise) {
Yes, you're right. I guess it's a matter of taste, I didn't want to change the behaviour if not necessary.

But if you look at it as a "bug", then it would make sense to change now.

2021-09-05 22:21 UTC, sindresorhus commented on index.js
> +		if (result && result instanceof Promise) {
Yeah, I see it as a bug.

2021-09-05 22:23 UTC, krystofwoldrich commented on index.js
> +		if (result && result instanceof Promise) {
I've used the  `Promise.resolve()` now.

2021-09-05 22:23 UTC, krystofwoldrich commented
@sindresorhus You can take a second look, I've made the changes you mentioned.

2021-09-17 13:34 UTC, merged

2021-09-17 13:52 UTC, fregante reviewed
A bit late to the party, but I see a major issue and a couple of improvements

2021-09-17 13:52 UTC, fregante commented on index.js
> +			return await Promise.resolve(result);
Why wrap this into a promise.resolve?

2021-09-17 13:52 UTC, fregante commented on index.js
> +			resultError = error;
Why not just clear the cache here?

2021-09-17 13:52 UTC, fregante commented on index.js
> +			cache.set(key, {
This means the cache is set AFTER the promise is fulfilled, which means these 2 calls will not be memoized:

```js 
void memFetch()
void memFetch()
```

2021-09-17 13:52 UTC, fregante commented on index.js
> +			if (!cachePromiseRejection && resultError) {
This position means that the cache is being set and then immediately deleted 🤷‍♂️

2021-09-17 14:46 UTC, fregante commented on index.js
> +			cache.set(key, {
To achieve both initial call memoization *and* move the start time to the fulfillment, it'd have to first store the call without expiration _and then_ re-add it with the right expiration once it fulfills.

2021-09-17 14:52 UTC, krystofwoldrich commented on index.js
> +			return await Promise.resolve(result);
True, that will make it cleaner.

2021-09-17 15:01 UTC, krystofwoldrich commented on index.js
> +			resultError = error;
I think this is only a matter of preference.
I see this as a more clear approach to have only one cache set.

2021-09-17 15:05 UTC, krystofwoldrich commented on index.js
> +			cache.set(key, {
I think if someone wants this behaviour there is mem that does exactly that.

2021-09-17 15:06 UTC, krystofwoldrich commented on index.js
> +			if (!cachePromiseRejection && resultError) {
True, this if could be written differently, so cache is set only when it should be.

2021-09-18 16:26 UTC, sindresorhus commented on index.js
> +			cache.set(key, {
It's totally valid to start multiple promises at the same time though. I agree with @fregante that this is a regression.

2021-09-18 16:27 UTC, sindresorhus commented on index.js
> +			cache.set(key, {
> Since it should be oriented on promise function and this is more not promise usecase.

I don't think @fregante made it clear enough in that example, but those are async functions.

2021-09-18 17:05 UTC, krystofwoldrich commented on index.js
> +			cache.set(key, {
OK, guys, I've created a new PR (https://github.com/sindresorhus/p-memoize/pull/25) which solves this.

2021-09-18 17:06 UTC, krystofwoldrich commented on index.js
> +			if (!cachePromiseRejection && resultError) {
Also, this is solved here https://github.com/sindresorhus/p-memoize/pull/25

2021-09-18 17:06 UTC, krystofwoldrich commented on index.js
> +			return await Promise.resolve(result);
I removed the resolve here https://github.com/sindresorhus/p-memoize/pull/25