Fix consecutive non awaited calls
sindresorhus/p-memoize pull request #25
Opened 2021-09-18 17:04 UTC by krystofwoldrich

Based on our discussion after merging PR https://github.com/sindresorhus/p-memoize/pull/24 I'm opening a new one hopefully solving mentioned issues.

2021-09-18 17:21 UTC, fregante requested changes

2021-09-18 17:21 UTC, fregante commented on index.js
>  		const result = fn.apply(this, arguments_);
For clarity

```suggestion
		const promise = fn.apply(this, arguments_);
```

2021-09-18 17:21 UTC, fregante commented on index.js
> +				});
```suggestion
			} else if (maxAge) {
				// Promise fulfilled, so start the timer
				cache.set(key, {
					data: result,
					maxAge: Date.now() + maxAge
				});
```

2021-09-18 17:21 UTC, fregante commented on index.js
>  		} finally {
@sindresorhus Since we're capturing the error, I think we should use `Promise.allSettled`, what do you think? This feels cleaner:

```js
const [{value, reason}] = await Promise.allSettled([promise])
if (reason && !cachePromiseRejection) {
	cache.delete(key);
} else if (maxAge) {
	cache.set(key, {
		data: promise,
		maxAge: Date.now()
	});
}

return promise;
```

2021-09-18 17:25 UTC, krystofwoldrich commented on index.js
>  		} finally {
I haven't used `allSettled` before but it looks super clean in this case.

2021-09-18 17:28 UTC, fregante commented on index.js
>  		} finally {
Once added p-memoize will also need to bump to a minimum of Node 12 and therefore ESM https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

2021-09-18 17:33 UTC, sindresorhus commented on index.js
>  		} finally {
I can handle the Node.js bumping and ESM stuff after this PR.

2021-09-18 20:07 UTC, krystofwoldrich commented on index.js
>  		const result = fn.apply(this, arguments_);
Done.

2021-09-18 20:08 UTC, krystofwoldrich commented on index.js
> +				});
Done.

2021-09-19 06:34 UTC, merged

2021-09-19 06:35 UTC, sindresorhus commented
Thanks for fixing, @krystofwoldrich 👍

2021-09-19 09:33 UTC, krystofwoldrich commented
Thanks for the prompt comments and reviews. @sindresorhus and @fregante